### ISSUE TITLE
Чтение не очень надёжно

### ISSUE THREAD

**Issue by alex85k** [alexeycas6/Dijkstra-Warshall#1]
Если будет другая расстановка пробелов и табуляций, граф не считается.

Проще  всего решить проблему поиском регулярных выражений. Пример:
```c++
	std::regex re("(\\d+)\\s+(\\w*).*");

	std::string s = "1234 dskjdsgfdj slf";

	std::smatch m;
	if (std::regex_match(s, m, re)) {
		string q(m[2].first, m[2].second);
		cout << m[1].str()<<endl;
		cout << m[2].str() << endl;
	}
```

**Comment by alex85k** [comment]
Кстати, создавать объект Edge только если найден fill - совсем не надёжно.

**Comment by alexeycas6** [comment]
Убрал считывание fill вообще за ненадобностью (в конструкторе присваивается по умолчанию чёрный), перевел поиск на регулярные выражения.
