### ISSUE TITLE
API для добавления комментариев в граф 

### ISSUE THREAD

**Issue by alex85k** [alexeycas6/Dijkstra-Warshall#4]
Хотим на каждом шаге выводить состояние очереди или что-то ещё (не относящееся к вершине).
 
Предлагаю следующий способ. При чтении отлавливаем узлы с меткой MSG_*
```
	node
	[
		id	6
		label	"MSG_QUEUE"
```
и не включаем их в граф (на кол-во вершин тоже невлияет).

При записи заносим в label (или вложенный text) у таких вершин содержимое отдельного ассоциативного массива комментариев.
```
  map <string,string> comments;
...
comments[label] =...
...

```
записать ``comments["MSG_QUEUE"]`` вместо "MSG_QUEUE".

**Comment by alexeycas6** [comment]
Выводится айдишники и цены вершин,находящихся в очереди
