### ISSUE TITLE
Последние улучшения

### ISSUE THREAD

**Issue by alex85k** [alexeycas6/Dijkstra-Warshall#5]
Тут лучше ориентироваться по метке (label), а не по форме узла:
https://github.com/alexeycas6/Dijkstra-Warshall/blob/master/Parser/Parser/Graph.cpp#L44

В этот момент мы уже точно знаем номер узла после сортирвки:
https://github.com/alexeycas6/Dijkstra-Warshall/blob/master/Parser/Parser/Graph.cpp#L202
(первый найденный - n, потом n-1 ...)

А в стеке лучше хранить путь от начальной вершины (добавлять при входе в dfs, убирать при выходе).

Должно работать на случайных графах из yed.

А так всё отлично!

**Comment by alexeycas6** [comment]
Обновлено
